DB_DRIVER = "postgres"
DB_HOST = "localhost"
DB_USER = "postgres"
DB_PASSWORD = "postgres"
DB_NAME = "sku_alerts"
DB_PORT = 5432
LLM = "defog/llama-3-sqlcoder-8b"
LLM_API_KEY = ""
LLM_ENDPOINT = "localhost:11434"
LLM_BACKEND = "ollama"
MODEL = "llama3.2:1b"
